version: '3'

services:
    web_server:
        build: web_server
        ports:
          - 80:80
          - 443:443
        volumes:
          - ./web_server/nginx.conf:/etc/nginx/nginx.conf
        links:
          - api


    api:
        build: api
        volumes:
          - ./api/src:/meep/api/src
          - ./api/tests:/meep/api/tests
        expose:
          - 8000
        ports:
          - 8000:8000
        depends_on:
          - db
          - test_db
        environment:
          - DEV_DATABASE_URL=postgresql://meep:supersafe@db:5432/meep_api
          - TEST_DATABASE_URL=postgresql://meep:supersafe@test_db:5432/test_meep_api
        links:
          - db
          - test_db


    db:
        image: kartoza/postgis
        environment:
          - POSTGRES_USER=meep
          - POSTGRES_PASSWORD=supersafe
          - POSTGRES_DB=meep_api
        volumes:
          - "postgres_data:/var/lib/postgresql/data"

    test_db:
        image: kartoza/postgis
        environment:
            - POSTGRES_USER=meep
            - POSTGRES_PASSWORD=supersafe
            - POSTGRES_DB=test_meep_api

volumes:
    postgres_data:
