version: '3'

services:
    web_server:
        build: web_server
        ports:
          - 80:80
          - 443:443
        volumes:
          - ./web_server/nginx.conf:/etc/nginx/nginx.conf
        links:
          - api


    api:
        build: api
        volumes:
          - ./api/src:/meep/api/src
          - ./api/tests:/meep/api/tests
        expose:
          - 8000
        ports:
          - 8000:8000
        depends_on:
          - db
          - test_db
        environment:
          - PRIVATE_KEY=\xc2\xacR\x97P.t\xffrF\x7f\xde"\xb4\n\xa9\x82\x9d\xba\xdb,,\x0e\x07
          - DEV_DATABASE_URL=postgresql://meep:supersafe@db:5432/meep_api
          - TEST_DATABASE_URL=postgresql://meep:supersafe@test_db:5432/test_meep_api
          - TOKEN_EXPIRATION=5
        links:
          - db
          - test_db


    db:
        image: postgres:11.3
        environment:
          - POSTGRES_USER=meep
          - POSTGRES_PASSWORD=supersafe
          - POSTGRES_DB=meep_api
        volumes:
          - "postgres_data:/var/lib/postgresql/data"

    test_db:
        image: postgres:11.3
        environment:
            - POSTGRES_USER=meep
            - POSTGRES_PASSWORD=supersafe
            - POSTGRES_DB=test_meep_api

volumes:
    postgres_data:
