version: '3'

services:
    web_server:
        build: web_server
        ports:
          - 80:80
          - 443:443
        volumes:
          - ./web_server/nginx.conf:/etc/nginx/nginx.conf
        links:
          - backend
    backend:
        build: ./src

        volumes:
          - ./src:/meep/api/src
          - ./src/tests:/meep/api/tests
        expose:
          - 8000
        ports:
          - 8000:8000
        depends_on:
          - db
        links:
          - db
    db:
        env_file: .env
        image: kartoza/postgis
        environment:
          - "POSTGRES_HOST_AUTH_METHOD=trust"
          - POSTGRES_DBNAME=${PG_DBNAME}
          - POSTGRES_USER=${PG_USER}
          - POSTGRES_PASS=${PG_PASS}
          - POSTGRES_HOSTNAME=${PG_HOSTNAME}
        volumes:
          - "postgres_data:/var/lib/postgresql/data"

volumes:
    postgres_data:
